### ISSUE TITLE
Pipeline instances in the Azure DevOps server are not deleted

### ISSUE THREAD

**Issue by clemlesne** [clemlesne/blue-agent#214]
## Business impact

UI is slow because of numerous builds in the history.

## Issue

Pipeline instances in the Azure DevOps server are not deleted. They remain indefinitely in the UI.

![image](https://github.com/clemlesne/azure-pipelines-agent/assets/6141105/4f210d1b-8c45-4281-b295-dc93e3138742)

## Proposed solution

Clean-up the entry from the startup script, catching exit codes.

## To-do

- [x] Implement the clean-up step in `script.sh` (Linux) (c8288f26a086defe86d6a5449a72f798d4d96014)
- [x] Implement the clean-up step in `script.ps1` (Windows) (c631c74a933496c43ef0f585388f53adbae8253f)
- [x] Remove the now deprecated `config.cmd remove` call in the Kubernetes lifecycle policy, but keep the _clean the pipeline workspace_ step (c8288f26a086defe86d6a5449a72f798d4d96014, c631c74a933496c43ef0f585388f53adbae8253f)

**Comment by clemlesne** [comment]
Related: https://github.com/clemlesne/azure-pipelines-agent/pull/182

**Comment by clemlesne** [comment]
Merged to develop in 69a3460d6420fb7d37c8c0ede4e45315fa154110. Will be included in the new feat version.

**Comment by clemlesne** [comment]
Done in 69a3460d6420fb7d37c8c0ede4e45315fa154110. Integration tests added.
